# Generated by Django 2.2.4 on 2019-08-11 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Feature'), (1, 'Bug')])),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'Normal'), (1, 'High'), (2, 'Low')])),
                ('estimate_time', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
