# Generated by Django 2.2.4 on 2019-08-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_user_list', 'Can view user list')]},
        ),
    ]
