# Generated by Django 2.2.4 on 2019-08-27 16:41

from django.db import migrations


def apply_migration(apps, schema_editor):
    admin_perms = ('add_user', 'change_user', 'delete_user', 'add_project', 'change_project', 'delete_project',
                   'add_task', 'delete_task', 'change_log', 'delete_log', 'view_user_list')
    Group = apps.get_model('auth', 'Group')
    admin = Group.objects.create(name='admin')
    Group.objects.create(name='user')
    Permission = apps.get_model('auth', 'Permission')
    perm_ids = Permission.objects.filter(codename__in=admin_perms).values_list('id', flat=True)
    admin.permissions.set(perm_ids)


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            'admin_1',
            'user_1'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190819_2031'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
