# Generated by Django 2.2.4 on 2019-08-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_time', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
